package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_entities = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_entity = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_property = new ConceptPresentationBuilder().shortDesc("entity property").create();
  private final ConceptPresentation props_relation = new ConceptPresentationBuilder().shortDesc("Relations between entities").create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.entities:
        return props_entities;
      case LanguageConceptSwitch.entity:
        return props_entity;
      case LanguageConceptSwitch.property:
        return props_property;
      case LanguageConceptSwitch.relation:
        return props_relation;
    }
    return null;
  }
}
