package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_5308855361891653417(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL, 0x139dd5d6acdd14f3L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891748758(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL, "NewLanguage.structure.entity"), false, false), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL, 0x139dd5d6acdd14f3L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891680027(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f2L, 0x139dd5d6acdbf6f3L, "type"));
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891684143(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f2L, 0x139dd5d6acdbf6f5L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891819046(final PropertyMacroContext _context) {
    String tipo = "--";
    if (SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f8L, 0x139dd5d6acdbf6f9L, "type")).equals("Val")) {
      tipo = "*--";
    }
    return tipo;
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891999572(final PropertyMacroContext _context) {
    String cardinality = "\"0..*\"";
    if (SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f8L, 0x139dd5d6acdbf6feL, "cardinality")).equals("+")) {
      cardinality = "\"1\"";
    }
    return cardinality;
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891718207(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f8L, 0x139dd5d6acdbf702L, "EntityNameRef"));
  }
  public static Object propertyMacro_GetPropertyValue_5308855361891722064(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f8L, 0x139dd5d6acdbf6fbL, "name"));
  }
  public static Iterable<SNode> sourceNodesQuery_5308855361891662014(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6b9L, 0x139dd5d6acdbf6bbL, "listOfEntities"));
  }
  public static Iterable<SNode> sourceNodesQuery_5308855361891697217(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL, 0x139dd5d6acdbf70dL, "listOfProperties"));
  }
  public static Iterable<SNode> sourceNodesQuery_5308855361891711478(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL, 0x139dd5d6acdbf70fL, "listOfRelations"));
  }
}
