package NewLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new entities_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new entity_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new property_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new relation_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6b9L), MetaIdFactory.conceptId(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6baL), MetaIdFactory.conceptId(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f2L), MetaIdFactory.conceptId(0x4ad2e0f6d3fb4cf4L, 0xa3324d84e2a36372L, 0x139dd5d6acdbf6f8L)).seal();
}
